# Generated by Django 3.2.4 on 2021-07-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_sub',
            field=models.IntegerField(default=0),
        ),
    ]
